### ISSUE TITLE
【アプリキャンペーン】3月前半ホワイトデー_2017/3/1～14

### ISSUE THREAD

**Issue by SeiyamaKarin** [SeiyamaKarin/white-day#2]

**Comment by tonorie** [comment]
## FB
全体的な構成は良いと思います！
ただ、ちょっと新しさやひねりが足りないな〜と。
考える時間たっぷりあると思うので、じっくりテキストとか考えてもいいのではと思いました。
あと、オリジナル飴→オリジナルキャンディー(オリジナルCandy)とかの方が聞こえや見栄えはいいと思う。
